#!/bin/bash
# =========================================
# ALIN 元数据生成器 (Metadata Indexer)
# =========================================
#
# 功能:
# - 为每个 Inode 自动生成 .meta 文本文件
# - 包含: 函数功能描述、输入格式、输出格式
# - 使用简单的解析从源码提取注释
#
# 使用方式:
#   ./alin_meta.sh <node_name> <binary_path>

set -e

# 配置
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SRC_DIR="$PROJECT_DIR/alin/src"
META_DIR="$PROJECT_DIR/alin/meta"

# 颜色输出
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[META]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }

# 参数
NODE_NAME="$1"
BINARY_PATH="$2"

if [ -z "$NODE_NAME" ]; then
    echo "Usage: $0 <node_name> [binary_path]"
    exit 1
fi

# 确保目录存在
mkdir -p "$META_DIR"

# 源文件路径 (支持子目录)
SRC_FILE=$(find "$PROJECT_DIR/alin/src" -name "${NODE_NAME}.c" 2>/dev/null | head -1)

if [ -z "$SRC_FILE" ] || [ ! -f "$SRC_FILE" ]; then
    log_info "Source file not found: ${NODE_NAME}.c"
    exit 1
fi

# 提取函数描述 (从文件头注释)
extract_description() {
    # 提取 /** ... */ 之间的内容
    awk '/^\/\*\*$/,/^\*\/$/' "$SRC_FILE" | \
        grep -E '^\s*\*\s' | \
        sed 's/^\s*\*\s*//' | \
        head -1
}

# 提取输入格式
extract_input() {
    awk '/^\/\*\*$/,/^\*\/$/' "$SRC_FILE" | \
        grep -i '输入:' | \
        sed 's/.*输入:\s*//'
}

# 提取输出格式
extract_output() {
    awk '/^\/\*\*$/,/^\*\/$/' "$SRC_FILE" | \
        grep -i '输出:' | \
        sed 's/.*输出:\s*//'
}

# 计算 hash
if [ -n "$BINARY_PATH" ] && [ -f "$BINARY_PATH" ]; then
    HASH=$(basename "$BINARY_PATH" | sed "s/^${NODE_NAME}_//" )
    INODE=$(ls -i "$BINARY_PATH" | awk '{print $1}')
else
    HASH="unknown"
    INODE="unknown"
fi

# 生成时间戳
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# 提取信息
DESCRIPTION=$(extract_description)
INPUT_FORMAT=$(extract_input)
OUTPUT_FORMAT=$(extract_output)

# 生成 .meta 文件
META_FILE="$META_DIR/${NODE_NAME}.meta"

log_info "Generating metadata for: $NODE_NAME"

cat > "$META_FILE" << EOF
# ALIN Node Metadata
# Auto-generated by alin_meta.sh

[node]
name = $NODE_NAME
hash = $HASH
inode = $INODE
source = alin/src/${NODE_NAME}.c
generated = $TIMESTAMP

[description]
$DESCRIPTION

[interface]
input = $INPUT_FORMAT
output = $OUTPUT_FORMAT

[protocol]
encoding = json
streaming = stdin/stdout

[dependencies]
none
EOF

log_success "Generated: $META_FILE"

# 显示内容预览
echo ""
cat "$META_FILE"
